version: "2"
services:
  twoboards:
    build:
      context: ../..
      dockerfile: environment/dev/Dockerfile
    working_dir: /app
    volumes:
      - ../..:/app
      - ../../../py-trello-mock:/py-trello-mock
      - ../../../py-trello:/py-trello
    environment:
      - API_KEY
      - API_SECRET
      - TOKEN
      - PRODUCT_BOARD_ID
      - TECH_BOARD_ID
      - PRE_PIPELINE
      - PIPELINE
      - POST_PIPELINE
      - PYTHONPATH=.:/py-trello:/py-trello-mock
    command: "python /app/cli.py sync"
