version: "2"
services:
  twoboards:
    build:
      context: ../..
      dockerfile: environment/dev/Dockerfile
    working_dir: /app
    volumes:
      - ../..:/app
    environment:
      - API_KEY
      - API_SECRET
      - TOKEN
      - PRODUCT_BOARD_ID
      - TECH_BOARD_ID
      - PRE_PIPELINE
      - PIPELINE
      - POST_PIPELINE
    command: "python /app/cli.py sync"
